const foods = [
  {name:"Manzana", proteinPerUnit:0.003, caloriesPerUnit:0.52, unitType:"g"},
  {name:"Huevo", proteinPerUnit:0.13, caloriesPerUnit:1.43, unitType:"g"},
  {name:"Leche entera", proteinPerUnit:0.034, caloriesPerUnit:0.61, unitType:"ml"},
  {name:"Arroz blanco cocido", proteinPerUnit:0.027, caloriesPerUnit:1.3, unitType:"g"},
  {name:"Pollo cocido", proteinPerUnit:0.31, caloriesPerUnit:1.65, unitType:"g"},
  {name:"Pan blanco", proteinPerUnit:0.08, caloriesPerUnit:2.65, unitType:"g"},
  {name:"Banana", proteinPerUnit:0.013, caloriesPerUnit:0.89, unitType:"g"},
  {name:"Agua", proteinPerUnit:0, caloriesPerUnit:0, unitType:"ml"},
  {name:"Aceite de oliva", proteinPerUnit:0, caloriesPerUnit:8.84, unitType:"g"},
  {name:"Carne de res", proteinPerUnit:0.26, caloriesPerUnit:2.5, unitType:"g"},
  {name:"Lechuga", proteinPerUnit:0.014, caloriesPerUnit:0.15, unitType:"g"},
  {name:"Tomate", proteinPerUnit:0.009, caloriesPerUnit:0.18, unitType:"g"},
  {name:"Queso cheddar", proteinPerUnit:0.25, caloriesPerUnit:4.03, unitType:"g"},
  {name:"Yogur natural", proteinPerUnit:0.035, caloriesPerUnit:0.59, unitType:"g"},
  {name:"Café negro", proteinPerUnit:0.001, caloriesPerUnit:0.02, unitType:"ml"},
  {name:"Salmón", proteinPerUnit:0.20, caloriesPerUnit:2.08, unitType:"g"},
  {name:"Nuez", proteinPerUnit:0.15, caloriesPerUnit:6.54, unitType:"g"},
  {name:"Zanahoria", proteinPerUnit:0.009, caloriesPerUnit:0.41, unitType:"g"},
  {name:"Leche descremada", proteinPerUnit:0.034, caloriesPerUnit:0.35, unitType:"ml"},
  {name:"Miel", proteinPerUnit:0.003, caloriesPerUnit:3.04, unitType:"g"},
  
  // Más alimentos comunes en México:
  {name:"Frijol cocido", proteinPerUnit:0.09, caloriesPerUnit:1.4, unitType:"g"},
  {name:"Maíz blanco cocido", proteinPerUnit:0.03, caloriesPerUnit:1.0, unitType:"g"},
  {name:"Chile jalapeño", proteinPerUnit:0.02, caloriesPerUnit:0.4, unitType:"g"},
  {name:"Cebolla", proteinPerUnit:0.009, caloriesPerUnit:0.40, unitType:"g"},
  {name:"Aguacate", proteinPerUnit:0.02, caloriesPerUnit:1.6, unitType:"g"},
  {name:"Carne de cerdo", proteinPerUnit:0.27, caloriesPerUnit:2.42, unitType:"g"},
  {name:"Pescado tilapia", proteinPerUnit:0.20, caloriesPerUnit:1.1, unitType:"g"},
  {name:"Jitomate", proteinPerUnit:0.009, caloriesPerUnit:0.18, unitType:"g"},
  {name:"Calabacita", proteinPerUnit:0.010, caloriesPerUnit:0.17, unitType:"g"},
  {name:"Nopal", proteinPerUnit:0.014, caloriesPerUnit:0.16, unitType:"g"},
  {name:"Chile serrano", proteinPerUnit:0.018, caloriesPerUnit:0.35, unitType:"g"},
  {name:"Cilantro", proteinPerUnit:0.02, caloriesPerUnit:0.23, unitType:"g"},
  {name:"Frijol negro cocido", proteinPerUnit:0.09, caloriesPerUnit:1.3, unitType:"g"},
  {name:"Tortilla de maíz", proteinPerUnit:0.07, caloriesPerUnit:1.6, unitType:"g"},
  {name:"Queso fresco", proteinPerUnit:0.21, caloriesPerUnit:2.4, unitType:"g"},
  {name:"Leche evaporada", proteinPerUnit:0.033, caloriesPerUnit:0.71, unitType:"ml"},
  {name:"Jugo de naranja", proteinPerUnit:0.007, caloriesPerUnit:0.45, unitType:"ml"},
  {name:"Chocolate oscuro (70%)", proteinPerUnit:0.08, caloriesPerUnit:5.46, unitType:"g"},
  {name:"Tuna (fruta del nopal)", proteinPerUnit:0.04, caloriesPerUnit:0.41, unitType:"g"},
  {name:"Papa blanca cocida", proteinPerUnit:0.02, caloriesPerUnit:0.77, unitType:"g"},
  {name:"Camote cocido", proteinPerUnit:0.015, caloriesPerUnit:0.86, unitType:"g"},
  {name:"Atún enlatado (agua)", proteinPerUnit:0.23, caloriesPerUnit:1.0, unitType:"g"},
  {name:"Chorizo", proteinPerUnit:0.25, caloriesPerUnit:3.5, unitType:"g"},
  {name:"Camarón cocido", proteinPerUnit:0.24, caloriesPerUnit:1.0, unitType:"g"},
  {name:"Pan de dulce", proteinPerUnit:0.06, caloriesPerUnit:3.2, unitType:"g"},
  {name:"Café con leche", proteinPerUnit:0.02, caloriesPerUnit:0.35, unitType:"ml"},
  {name:"Tequila (alcohólico)", proteinPerUnit:0, caloriesPerUnit:2.5, unitType:"ml"},
  {name:"Mezcal (alcohólico)", proteinPerUnit:0, caloriesPerUnit:2.6, unitType:"ml"},
  {name:"Refresco cola", proteinPerUnit:0, caloriesPerUnit:0.42, unitType:"ml"},
  {name:"Salsa roja", proteinPerUnit:0.01, caloriesPerUnit:0.2, unitType:"g"},
  {name:"Salsa verde", proteinPerUnit:0.01, caloriesPerUnit:0.2, unitType:"g"},
  {name:"Pulque", proteinPerUnit:0.01, caloriesPerUnit:0.4, unitType:"ml"},
  {name:"Elote cocido", proteinPerUnit:0.03, caloriesPerUnit:1.2, unitType:"g"},
  {name:"Champiñones", proteinPerUnit:0.03, caloriesPerUnit:0.22, unitType:"g"},
  {name:"Frutas secas mixtas", proteinPerUnit:0.15, caloriesPerUnit:6.0, unitType:"g"},
  {name:"Agua de jamaica", proteinPerUnit:0, caloriesPerUnit:0.2, unitType:"ml"},
  {name:"Agua de horchata", proteinPerUnit:0.01, caloriesPerUnit:0.3, unitType:"ml"},
  {name:"Pescado basa", proteinPerUnit:0.18, caloriesPerUnit:1.0, unitType:"g"},
  {name:"Cerveza", proteinPerUnit:0.005, caloriesPerUnit:0.43, unitType:"ml"},
  {name:"Carne de pollo crudo", proteinPerUnit:0.20, caloriesPerUnit:1.1, unitType:"g"},
  {name:"Aguacate hass", proteinPerUnit:0.02, caloriesPerUnit:1.6, unitType:"g"},
  {name:"Cacahuate", proteinPerUnit:0.25, caloriesPerUnit:5.7, unitType:"g"},
  {name:"Sopa de tortilla", proteinPerUnit:0.05, caloriesPerUnit:0.9, unitType:"g"},
  {name:"Tamales de elote", proteinPerUnit:0.07, caloriesPerUnit:1.8, unitType:"g"},
  {name:"Tlayuda (Oaxaca)", proteinPerUnit:0.06, caloriesPerUnit:3.0, unitType:"g"},
  {name:"Carnitas", proteinPerUnit:0.25, caloriesPerUnit:3.2, unitType:"g"},
  {name:"Barbacoa", proteinPerUnit:0.28, caloriesPerUnit:2.8, unitType:"g"},
  {name:"Chiles en nogada", proteinPerUnit:0.06, caloriesPerUnit:2.2, unitType:"g"},
  {name:"Pozole", proteinPerUnit:0.04, caloriesPerUnit:0.8, unitType:"g"},
  {name:"Salsa de mole", proteinPerUnit:0.04, caloriesPerUnit:1.0, unitType:"g"},
  {name:"Chilaquiles", proteinPerUnit:0.07, caloriesPerUnit:2.2, unitType:"g"},
  {name:"Tamales de pollo", proteinPerUnit:0.07, caloriesPerUnit:2.0, unitType:"g"},

  // Otros mas a ver si cierto:

    {name:"Calabaza", proteinPerUnit:0.009, caloriesPerUnit:0.26, unitType:"g"},
  {name:"Chayote", proteinPerUnit:0.008, caloriesPerUnit:0.19, unitType:"g"},
  {name:"Papa cambray", proteinPerUnit:0.02, caloriesPerUnit:0.77, unitType:"g"},
  {name:"Elote tierno", proteinPerUnit:0.03, caloriesPerUnit:1.2, unitType:"g"},
  {name:"Coliflor", proteinPerUnit:0.02, caloriesPerUnit:0.25, unitType:"g"},
  {name:"Brócoli", proteinPerUnit:0.028, caloriesPerUnit:0.34, unitType:"g"},
  {name:"Espinaca", proteinPerUnit:0.029, caloriesPerUnit:0.23, unitType:"g"},
  {name:"Acelga", proteinPerUnit:0.02, caloriesPerUnit:0.19, unitType:"g"},
  {name:"Betabel", proteinPerUnit:0.015, caloriesPerUnit:0.43, unitType:"g"},
  {name:"Nopal fresco", proteinPerUnit:0.014, caloriesPerUnit:0.17, unitType:"g"},
  {name:"Ajo", proteinPerUnit:0.06, caloriesPerUnit:1.49, unitType:"g"},
  {name:"Cebollín", proteinPerUnit:0.02, caloriesPerUnit:0.27, unitType:"g"},
  {name:"Pepino", proteinPerUnit:0.007, caloriesPerUnit:0.16, unitType:"g"},
  {name:"Rábano", proteinPerUnit:0.01, caloriesPerUnit:0.16, unitType:"g"},
  {name:"Jícama", proteinPerUnit:0.01, caloriesPerUnit:0.38, unitType:"g"},
  {name:"Aguacate criollo", proteinPerUnit:0.02, caloriesPerUnit:1.6, unitType:"g"},
  {name:"Chile poblano", proteinPerUnit:0.01, caloriesPerUnit:0.29, unitType:"g"},
  {name:"Chile chipotle", proteinPerUnit:0.03, caloriesPerUnit:0.28, unitType:"g"},
  {name:"Chile guajillo", proteinPerUnit:0.04, caloriesPerUnit:1.3, unitType:"g"},
  {name:"Chile ancho", proteinPerUnit:0.03, caloriesPerUnit:1.2, unitType:"g"},
  {name:"Perejil", proteinPerUnit:0.03, caloriesPerUnit:0.36, unitType:"g"},
  {name:"Albahaca", proteinPerUnit:0.03, caloriesPerUnit:0.23, unitType:"g"},
  {name:"Orégano", proteinPerUnit:0.09, caloriesPerUnit:3.2, unitType:"g"},
  {name:"Laurel", proteinPerUnit:0.07, caloriesPerUnit:3.3, unitType:"g"},
  {name:"Tomatillo", proteinPerUnit:0.02, caloriesPerUnit:0.32, unitType:"g"},
  {name:"Chícharo cocido", proteinPerUnit:0.05, caloriesPerUnit:0.81, unitType:"g"},
  {name:"Lentejas cocidas", proteinPerUnit:0.09, caloriesPerUnit:1.1, unitType:"g"},
  {name:"Alubias cocidas", proteinPerUnit:0.09, caloriesPerUnit:1.2, unitType:"g"},
  {name:"Soja cocida", proteinPerUnit:0.13, caloriesPerUnit:1.6, unitType:"g"},
  {name:"Chía", proteinPerUnit:0.17, caloriesPerUnit:4.9, unitType:"g"},
  {name:"Ajonjolí", proteinPerUnit:0.18, caloriesPerUnit:5.6, unitType:"g"},
  {name:"Almendra", proteinPerUnit:0.21, caloriesPerUnit:6.0, unitType:"g"},
  {name:"Pistache", proteinPerUnit:0.20, caloriesPerUnit:5.7, unitType:"g"},
  {name:"Nuez de la india (cashew)", proteinPerUnit:0.18, caloriesPerUnit:5.5, unitType:"g"},
  {name:"Ciruela", proteinPerUnit:0.003, caloriesPerUnit:0.46, unitType:"g"},
  {name:"Guayaba", proteinPerUnit:0.02, caloriesPerUnit:0.68, unitType:"g"},
  {name:"Mango", proteinPerUnit:0.008, caloriesPerUnit:0.60, unitType:"g"},
  {name:"Papaya", proteinPerUnit:0.005, caloriesPerUnit:0.43, unitType:"g"},
  {name:"Piña", proteinPerUnit:0.005, caloriesPerUnit:0.50, unitType:"g"},
  {name:"Sandía", proteinPerUnit:0.003, caloriesPerUnit:0.30, unitType:"g"},
  {name:"Melón", proteinPerUnit:0.003, caloriesPerUnit:0.34, unitType:"g"},
  {name:"Durazno", proteinPerUnit:0.004, caloriesPerUnit:0.39, unitType:"g"},
  {name:"Cereza", proteinPerUnit:0.004, caloriesPerUnit:0.50, unitType:"g"},
  {name:"Fresa", proteinPerUnit:0.006, caloriesPerUnit:0.32, unitType:"g"},
  {name:"Zarzamora", proteinPerUnit:0.02, caloriesPerUnit:0.43, unitType:"g"},
  {name:"Arándano", proteinPerUnit:0.01, caloriesPerUnit:0.57, unitType:"g"},
  {name:"Higo", proteinPerUnit:0.01, caloriesPerUnit:0.74, unitType:"g"},
  {name:"Aceituna verde", proteinPerUnit:0.01, caloriesPerUnit:1.6, unitType:"g"},
  {name:"Aceituna negra", proteinPerUnit:0.01, caloriesPerUnit:1.6, unitType:"g"},
  {name:"Yuca", proteinPerUnit:0.012, caloriesPerUnit:1.5, unitType:"g"},
  {name:"Plátano macho", proteinPerUnit:0.014, caloriesPerUnit:1.3, unitType:"g"},
  {name:"Harina de trigo", proteinPerUnit:0.1, caloriesPerUnit:3.6, unitType:"g"},
  {name:"Azúcar blanca", proteinPerUnit:0, caloriesPerUnit:4.0, unitType:"g"},
  {name:"Sal de mesa", proteinPerUnit:0, caloriesPerUnit:0, unitType:"g"},
  {name:"Levadura seca", proteinPerUnit:0.40, caloriesPerUnit:3.9, unitType:"g"},
  {name:"Gelatina sin sabor", proteinPerUnit:0.85, caloriesPerUnit:3.4, unitType:"g"},
  {name:"Mayonesa", proteinPerUnit:0.01, caloriesPerUnit:6.8, unitType:"g"},
  {name:"Mostaza", proteinPerUnit:0.04, caloriesPerUnit:1.7, unitType:"g"},
  {name:"Salsa catsup", proteinPerUnit:0.01, caloriesPerUnit:1.0, unitType:"g"},
  {name:"Salsa picante", proteinPerUnit:0.01, caloriesPerUnit:0.15, unitType:"g"},
  {name:"Helado de vainilla", proteinPerUnit:0.04, caloriesPerUnit:2.0, unitType:"g"},
  {name:"Yogur con frutas", proteinPerUnit:0.04, caloriesPerUnit:0.75, unitType:"g"},
  {name:"Crema ácida", proteinPerUnit:0.02, caloriesPerUnit:2.1, unitType:"g"},
  {name:"Queso panela", proteinPerUnit:0.18, caloriesPerUnit:2.3, unitType:"g"},
  {name:"Queso Oaxaca", proteinPerUnit:0.22, caloriesPerUnit:3.0, unitType:"g"},
  {name:"Queso manchego", proteinPerUnit:0.25, caloriesPerUnit:4.0, unitType:"g"},
  {name:"Carne de pavo", proteinPerUnit:0.29, caloriesPerUnit:1.2, unitType:"g"},
  {name:"Carne de pato", proteinPerUnit:0.19, caloriesPerUnit:2.3, unitType:"g"},
  {name:"Jamón de pavo", proteinPerUnit:0.17, caloriesPerUnit:1.5, unitType:"g"},
  {name:"Jamón de cerdo", proteinPerUnit:0.15, caloriesPerUnit:2.0, unitType:"g"},
  {name:"Salchicha", proteinPerUnit:0.12, caloriesPerUnit:3.0, unitType:"g"},
  {name:"Chistorra", proteinPerUnit:0.20, caloriesPerUnit:3.4, unitType:"g"},
  {name:"Chorizo vegetariano", proteinPerUnit:0.15, caloriesPerUnit:2.5, unitType:"g"},
  {name:"Tofu", proteinPerUnit:0.08, caloriesPerUnit:0.76, unitType:"g"},
  {name:"Tempeh", proteinPerUnit:0.19, caloriesPerUnit:2.0, unitType:"g"},
  {name:"Leche de almendra", proteinPerUnit:0.005, caloriesPerUnit:0.13, unitType:"ml"},
  {name:"Leche de soya", proteinPerUnit:0.03, caloriesPerUnit:0.4, unitType:"ml"},
  {name:"Agua mineral", proteinPerUnit:0, caloriesPerUnit:0, unitType:"ml"},
  {name:"Jugo de manzana", proteinPerUnit:0.001, caloriesPerUnit:0.47, unitType:"ml"},
  {name:"Jugo de piña", proteinPerUnit:0.001, caloriesPerUnit:0.50, unitType:"ml"},
  {name:"Jugo de uva", proteinPerUnit:0.001, caloriesPerUnit:0.69, unitType:"ml"},

   //Blkoque 3!!!

   {name:"Caldo de pollo", proteinPerUnit:0.01, caloriesPerUnit:0.15, unitType:"ml"},
  {name:"Caldo de res", proteinPerUnit:0.012, caloriesPerUnit:0.16, unitType:"ml"},
  {name:"Caldo de verduras", proteinPerUnit:0.005, caloriesPerUnit:0.10, unitType:"ml"},
  {name:"Sopa de fideos", proteinPerUnit:0.02, caloriesPerUnit:0.60, unitType:"g"},
  {name:"Crema de verduras", proteinPerUnit:0.02, caloriesPerUnit:0.70, unitType:"g"},
  {name:"Tortilla de harina", proteinPerUnit:0.06, caloriesPerUnit:2.5, unitType:"g"},
  {name:"Tostada de maíz", proteinPerUnit:0.07, caloriesPerUnit:3.0, unitType:"g"},
  {name:"Galleta María", proteinPerUnit:0.06, caloriesPerUnit:4.6, unitType:"g"},
  {name:"Pan integral", proteinPerUnit:0.09, caloriesPerUnit:2.4, unitType:"g"},
  {name:"Avena", proteinPerUnit:0.17, caloriesPerUnit:3.9, unitType:"g"},
  {name:"Trigo integral", proteinPerUnit:0.13, caloriesPerUnit:3.4, unitType:"g"},
  {name:"Cereal de maíz", proteinPerUnit:0.08, caloriesPerUnit:3.7, unitType:"g"},
  {name:"Cereal avena miel", proteinPerUnit:0.07, caloriesPerUnit:4.0, unitType:"g"},
  {name:"Cereal chocolate", proteinPerUnit:0.07, caloriesPerUnit:4.1, unitType:"g"},
  {name:"Granola", proteinPerUnit:0.07, caloriesPerUnit:4.5, unitType:"g"},
  {name:"Pan rústico", proteinPerUnit:0.08, caloriesPerUnit:2.6, unitType:"g"},
  {name:"Bagel", proteinPerUnit:0.09, caloriesPerUnit:2.7, unitType:"g"},
  {name:"Pan pita", proteinPerUnit:0.08, caloriesPerUnit:2.6, unitType:"g"},
  {name:"Pan francés", proteinPerUnit:0.08, caloriesPerUnit:2.7, unitType:"g"},
  {name:"Pan integral", proteinPerUnit:0.09, caloriesPerUnit:2.5, unitType:"g"},
  {name:"Crema de cacahuate", proteinPerUnit:0.25, caloriesPerUnit:5.9, unitType:"g"},
  {name:"Nutella", proteinPerUnit:0.05, caloriesPerUnit:5.3, unitType:"g"},
  {name:"Mermelada de fresa", proteinPerUnit:0.0, caloriesPerUnit:2.6, unitType:"g"},
  {name:"Pan de caja light", proteinPerUnit:0.08, caloriesPerUnit:2.1, unitType:"g"},
  {name:"Queso crema", proteinPerUnit:0.05, caloriesPerUnit:3.3, unitType:"g"},
  {name:"Crema para café", proteinPerUnit:0.01, caloriesPerUnit:2.0, unitType:"g"},
  {name:"Yogur griego", proteinPerUnit:0.10, caloriesPerUnit:0.6, unitType:"g"},
  {name:"Yogur de soya", proteinPerUnit:0.06, caloriesPerUnit:0.5, unitType:"g"},
  {name:"Leche deslactosada", proteinPerUnit:0.033, caloriesPerUnit:0.60, unitType:"ml"},
  {name:"Chocomilk", proteinPerUnit:0.03, caloriesPerUnit:0.70, unitType:"ml"},
  {name:"Malteada", proteinPerUnit:0.05, caloriesPerUnit:1.2, unitType:"ml"},
  {name:"Soda sabor naranja", proteinPerUnit:0, caloriesPerUnit:0.45, unitType:"ml"},
  {name:"Soda sabor limón", proteinPerUnit:0, caloriesPerUnit:0.42, unitType:"ml"},
  {name:"Leche sabor vainilla", proteinPerUnit:0.03, caloriesPerUnit:0.65, unitType:"ml"},
  {name:"Smoothie de fresa", proteinPerUnit:0.02, caloriesPerUnit:0.80, unitType:"ml"},
  {name:"Smoothie verde", proteinPerUnit:0.01, caloriesPerUnit:0.75, unitType:"ml"},
  {name:"Té verde", proteinPerUnit:0, caloriesPerUnit:0, unitType:"ml"},
  {name:"Té negro", proteinPerUnit:0, caloriesPerUnit:0, unitType:"ml"},
  {name:"Té chai latte", proteinPerUnit:0.02, caloriesPerUnit:0.70, unitType:"ml"},
  {name:"Capuchino", proteinPerUnit:0.02, caloriesPerUnit:0.80, unitType:"ml"},
  {name:"Espresso", proteinPerUnit:0.0, caloriesPerUnit:0.02, unitType:"ml"},
  {name:"Café americano", proteinPerUnit:0, caloriesPerUnit:0.02, unitType:"ml"},
  {name:"Café con crema", proteinPerUnit:0.01, caloriesPerUnit:1.0, unitType:"ml"},
  {name:"Batido de proteína", proteinPerUnit:0.20, caloriesPerUnit:1.2, unitType:"g"},
  {name:"Whey (polvo)", proteinPerUnit:0.80, caloriesPerUnit:4.0, unitType:"g"},
  {name:"Glutamina (polvo)", proteinPerUnit:1.0, caloriesPerUnit:4.0, unitType:"g"},
  {name:"Barra de proteína", proteinPerUnit:0.12, caloriesPerUnit:4.2, unitType:"g"},
  {name:"Barra de cereal", proteinPerUnit:0.05, caloriesPerUnit:4.5, unitType:"g"},
  {name:"Brownie", proteinPerUnit:0.05, caloriesPerUnit:4.8, unitType:"g"},
  {name:"Pastel de chocolate", proteinPerUnit:0.05, caloriesPerUnit:4.5, unitType:"g"},
  {name:"Panqué", proteinPerUnit:0.05, caloriesPerUnit:4.7, unitType:"g"},
  {name:"Pay de limón", proteinPerUnit:0.04, caloriesPerUnit:4.2, unitType:"g"},
  {name:"Flan", proteinPerUnit:0.04, caloriesPerUnit:1.9, unitType:"g"},
  {name:"Gelatina de fresa", proteinPerUnit:0.03, caloriesPerUnit:0.8, unitType:"g"},
  {name:"Paleta de yogurt", proteinPerUnit:0.02, caloriesPerUnit:0.6, unitType:"g"},
  {name:"Paleta de agua", proteinPerUnit:0, caloriesPerUnit:0.5, unitType:"g"},
  {name:"Agua de melon", proteinPerUnit:0.001, caloriesPerUnit:0.25, unitType:"ml"},
  {name:"Agua de piña", proteinPerUnit:0.001, caloriesPerUnit:0.30, unitType:"ml"},
  {name:"Agua de fresa", proteinPerUnit:0.001, caloriesPerUnit:0.24, unitType:"ml"},
  {name:"Leche de coco", proteinPerUnit:0.01, caloriesPerUnit:1.9, unitType:"ml"},
  {name:"Crema de coco", proteinPerUnit:0.01, caloriesPerUnit:2.1, unitType:"g"},
  {name:"Leche evaporada light", proteinPerUnit:0.033, caloriesPerUnit:0.55, unitType:"ml"},
  {name:"Crema para batir", proteinPerUnit:0.02, caloriesPerUnit:3.45, unitType:"g"},
  {name:"Queso doble crema", proteinPerUnit:0.22, caloriesPerUnit:4.0, unitType:"g"},
  {name:"Queso panela light", proteinPerUnit:0.19, caloriesPerUnit:2.2, unitType:"g"},
  {name:"Queso manchego light", proteinPerUnit:0.23, caloriesPerUnit:3.4, unitType:"g"},
  {name:"Queso fresco light", proteinPerUnit:0.20, caloriesPerUnit:2.0, unitType:"g"},

];
